In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
path = '/content/drive/MyDrive/Mecine Learning/Praktikum10'

In [3]:
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [5]:
df = pd.read_excel("/content/drive/MyDrive/Mecine Learning/Praktikum10/data/data_prediksi.xlsx")
print("Data Prediksi:")
display(df)

Data Prediksi:

     NIM Hasil Sebenarnya Hasil Prediksi
0  TI001            Lulus          Lulus
1  TI002            Lulus          Lulus
2  TI003            Lulus          Lulus
3  TI004            Lulus    Tidak Lulus
4  TI005            Lulus    Tidak Lulus
5  TI006      Tidak Lulus          Lulus
6  TI007      Tidak Lulus    Tidak Lulus
7  TI008      Tidak Lulus    Tidak Lulus
8  TI009      Tidak Lulus    Tidak Lulus
9  TI010      Tidak Lulus    Tidak Lulus

# Confusion Matrix

In [7]:
cm = confusion_matrix(df["Hasil Sebenarnya"], df["Hasil Prediksi"], labels=["Lulus", "Tidak Lulus"])

cm_df = pd.DataFrame(cm,
                     index=["Actual Lulus", "Actual Tidak Lulus"],
                     columns=["Pred Lulus", "Pred Tidak Lulus"])

print("\nConfusion Matrix:")
display(cm_df)

Confusion Matrix:

                    Pred Lulus  Pred Tidak Lulus
Actual Lulus                 3                 2
Actual Tidak Lulus           1                 4

## Hitung Accuracy, Precision, Recall

In [9]:
accuracy = accuracy_score(df["Hasil Sebenarnya"], df["Hasil Prediksi"])
precision = precision_score(df["Hasil Sebenarnya"], df["Hasil Prediksi"], pos_label="Lulus")
recall = recall_score(df["Hasil Sebenarnya"], df["Hasil Prediksi"], pos_label="Lulus")

print("Accuracy:", round(accuracy * 100, 2), "%")
print("Precision:", round(precision * 100, 2), "%")
print("Recall:", round(recall * 100, 2), "%")

Accuracy: 70.0 %
Precision: 75.0 %
Recall: 60.0 %